name: Build artifact

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: LabBox64/jdk-composite-action/jdk-composite-action@v0.0.2
      with:
        jdk-version: '15'
        jdk-distribution: 'adopt'

    - name: Maven Verify
      run: mvn -B clean verify
