name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: LabBox64/jdk-composite-action/jdk-build@v0.0.7
