name: Deploy Docker Image

on:
  push:
    branches:
      - 'main'

jobs:

  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: LabBox64/build-actions/packages/jdk-build@v1.0.7
      - uses: LabBox64/build-actions/packages/deploy-docker@v1.0.7
        with:
          registry-username: ${{secrets.DOCKER_HUB_USERNAME}}
          registry-password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - uses: LabBox64/action-autotag@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
