name: Deploy Docker Image

on:
  push:
    branches:
      - 'main'

jobs:

  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: LabBox64/build-actions/packages/jdk-build@v1.0.3
      - uses: LabBox64/build-actions/packages/jdk-deploy-docker@v1.0.3
        with:
          registry-username: ${{secrets.DOCKER_HUB_USERNAME}}
          registry-password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
